"""Digest generator — human-readable nightly report."""

import sqlite3
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List

from .models import RunStats, ANALYZER_VERSION, VNX_BASE, log


class DigestGenerator:
    """Generate a human-readable nightly digest markdown report."""

    def generate(self, run_date: str, run_stats: RunStats,
                 session_rows: List[dict], db_path: Path) -> str:
        lines = [
            f"# VNX Nightly Digest — {run_date}",
            "",
            "## Samenvatting",
            f"- **{run_stats.sessions_analyzed}** sessies geanalyseerd",
            f"- **{run_stats.sessions_deep}** sessies diep geanalyseerd (LLM)",
            f"- **{len(run_stats.suggestions)}** nieuwe verbeter-suggesties",
            f"- **{run_stats.total_tokens:,}** output tokens totaal",
            "",
        ]

        self._append_terminal_stats(session_rows, lines)
        self._append_suggestions(run_stats.suggestions, lines)

        trends = self._get_trends(db_path, run_date)
        if trends:
            lines.append("## Trends (laatste 7 dagen)")
            lines.append("")
            for trend_line in trends:
                lines.append(f"- {trend_line}")
            lines.append("")

        lines.append("---")
        lines.append(f"*Generated by VNX Conversation Analyzer v{ANALYZER_VERSION}*")
        return "\n".join(lines)

    def write_digest(self, markdown: str, run_date: str) -> Path:
        digest_dir = VNX_BASE / "reports" / "nightly"
        digest_dir.mkdir(parents=True, exist_ok=True)
        digest_path = digest_dir / f"digest_{run_date}.md"
        digest_path.write_text(markdown, encoding="utf-8")
        return digest_path

    def _append_terminal_stats(self, session_rows: List[dict], lines: List[str]):
        terminal_stats: Dict[str, dict] = {}
        for row in session_rows:
            t = row.get("terminal", "unknown")
            if t not in terminal_stats:
                terminal_stats[t] = {"sessions": 0, "input": 0, "output": 0,
                                     "cache_read": 0, "cache_create": 0}
            s = terminal_stats[t]
            s["sessions"] += 1
            s["input"] += row.get("total_input_tokens", 0)
            s["output"] += row.get("total_output_tokens", 0)
            s["cache_read"] += row.get("cache_read_tokens", 0)
            s["cache_create"] += row.get("cache_creation_tokens", 0)

        if not terminal_stats:
            return

        lines.append("## Token Overzicht")
        lines.append("")
        lines.append("| Terminal | Sessies | Input | Output | Cache Hit% |")
        lines.append("|----------|---------|-------|--------|------------|")
        for t in sorted(terminal_stats.keys()):
            s = terminal_stats[t]
            total_cache = s["cache_read"] + s["cache_create"]
            cache_pct = (s["cache_read"] / total_cache * 100) if total_cache > 0 else 0
            lines.append(
                f"| {t} | {s['sessions']} | "
                f"{self._fmt_tokens(s['input'])} | "
                f"{self._fmt_tokens(s['output'])} | "
                f"{cache_pct:.0f}% |"
            )
        lines.append("")

    def _append_suggestions(self, suggestions: List[dict], lines: List[str]):
        if not suggestions:
            return
        lines.append(f"## Verbeter Suggesties ({len(suggestions)} nieuw)")
        lines.append("")
        priority_order = {"critical": 0, "high": 1, "medium": 2, "low": 3}
        for sg in sorted(suggestions, key=lambda x: priority_order.get(x.get("priority", "medium"), 2)):
            prio = sg.get("priority", "medium").upper()
            cat = sg.get("category", "workflow")
            comp = sg.get("component", "")
            lines.append(f"### [{prio}] {cat.capitalize()}: {comp}")
            lines.append(f"**Huidige situatie**: {sg.get('current_behavior', 'N/A')}")
            lines.append(f"**Suggestie**: {sg.get('suggested_improvement', 'N/A')}")
            lines.append(f"**Bewijs**: {sg.get('evidence', 'N/A')}")
            lines.append("")

    @staticmethod
    def _fmt_tokens(n: int) -> str:
        if n >= 1_000_000:
            return f"{n / 1_000_000:.1f}M"
        if n >= 1_000:
            return f"{n / 1_000:.0f}K"
        return str(n)

    @staticmethod
    def _get_trends(db_path: Path, run_date: str) -> List[str]:
        trends = []
        try:
            conn = sqlite3.connect(db_path)
            conn.row_factory = sqlite3.Row
            cur = conn.cursor()

            week_ago = (datetime.strptime(run_date, "%Y-%m-%d") - timedelta(days=7)).strftime("%Y-%m-%d")
            prev_week = (datetime.strptime(run_date, "%Y-%m-%d") - timedelta(days=14)).strftime("%Y-%m-%d")

            cur.execute(
                "SELECT SUM(total_output_tokens) as total "
                "FROM session_analytics WHERE session_date >= ?", (week_ago,))
            row = cur.fetchone()
            this_week = (row["total"] or 0) if row else 0

            cur.execute(
                "SELECT SUM(total_output_tokens) as total "
                "FROM session_analytics WHERE session_date >= ? AND session_date < ?",
                (prev_week, week_ago))
            row = cur.fetchone()
            last_week = (row["total"] or 0) if row else 0

            if last_week > 0:
                change = ((this_week - last_week) / last_week) * 100
                arrow = "+" if change > 0 else ""
                trends.append(f"Token verbruik: {arrow}{change:.0f}% vs vorige week")

            cur.execute(
                "SELECT COUNT(*) as cnt FROM session_analytics "
                "WHERE session_date >= ? AND has_error_recovery = 1", (week_ago,))
            row = cur.fetchone()
            err_count = (row["cnt"] or 0) if row else 0
            trends.append(f"Error recovery sessies: {err_count} (laatste 7 dagen)")

            cur.execute(
                "SELECT primary_activity, COUNT(*) as cnt "
                "FROM session_analytics WHERE session_date >= ? "
                "GROUP BY primary_activity ORDER BY cnt DESC LIMIT 1", (week_ago,))
            row = cur.fetchone()
            if row:
                trends.append(f"Meest voorkomende activiteit: {row['primary_activity']} ({row['cnt']}x)")

            conn.close()
        except (sqlite3.Error, OSError) as exc:
            log("WARNING", f"Failed to load trends from DB: {exc}")
        return trends
